# Generated by Django 5.2.15 on 2026-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AIRTE', 'Airtel Money'), ('MPAMB', 'TNM Mpamba'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], help_text='Method used to pay this expense.', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
