# Generated by Django 5.2.15 on 2026-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_department_bankaccount_banktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AIRTE', 'Airtel Money'), ('MPAMB', 'TNM Mpamba'), ('CHEQUE', 'Cheque')], help_text='Method used to pay this expense.', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AIRTE', 'Airtel Money'), ('MPAMB', 'TNM Mpamba'), ('CHEQUE', 'Cheque')], help_text='Method used to pay this bill.', max_length=20),
        ),
    ]
