# Generated by Django 5.2.15 on 2026-06-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name'], 'permissions': [('assign_asset', 'Can assign asset'), ('return_asset', 'Can return asset'), ('schedule_maintenance', 'Can schedule maintenance')]},
        ),
    ]
