# Generated by Django 5.2.15 on 2026-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto‑generate (e.g., EMP-00001).', max_length=50, null=True, unique=True),
        ),
    ]
