# Generated by Django 5.2.15 on 2026-06-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_employee_number'),
        ('accounts', '0004_backfill_employee_numbers'),
    ]

    operations = [
    ]
