# Generated by Django 5.2.15 on 2026-06-26 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260625_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_seen', models.BooleanField(default=False)),
                ('tour_completed', models.BooleanField(default=False)),
                ('tour_completed_at', models.DateTimeField(blank=True, null=True)),
                ('tour_step_reached', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
