# Generated by Django 5.2.15 on 2026-06-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_useractivity_ip_address_and_more'),
        ('accounts', '0008_create_groups'),
    ]

    operations = [
    ]
