# Generated by Django 5.2.15 on 2026-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_sales_finance_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(default=10, help_text='Higher = more authority'),
        ),
    ]
