# Generated by Django 5.2.15 on 2026-06-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'permissions': [('receive_stock', 'Can receive stock'), ('issue_stock', 'Can issue stock'), ('transfer_stock', 'Can transfer stock'), ('adjust_stock', 'Can adjust stock'), ('view_stock_report', 'Can view stock reports')]},
        ),
    ]
