# Generated by Django 5.2.15 on 2026-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored Stock Issue Voucher for audit', null=True, upload_to='pdfs/stock_issues/'),
        ),
    ]
