"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse, NoReverseMatch

# ─── Build paths ──────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ─── Security ─────────────────────────────────────────────────────────────
SECRET_KEY = 'django-insecure-#*qkw^wd_uav7qfad^)v-*ovaey2g#hq2zuvihls4@r++w@d$f'
DEBUG = True
ALLOWED_HOSTS = []

# ─── Application definition ──────────────────────────────────────────────
INSTALLED_APPS = [
    # Unfold must come before admin
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    
    'daphne', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    'django_htmx',
    'axes',                     # Account lockout
    'channels',

    # Our apps
    'notifications',
    'accounts',
    'inventory',
    'procurement',
    'operations',
    'assets',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'axes.middleware.AxesMiddleware',          # Must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.tutorial_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ── Channels / ASGI ────────────────────────────────────
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

# ─── Database ─────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ─── Password validation ─────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ─── Internationalization ────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ─── Crispy Forms ────────────────────────────────────────────────────────
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ─── Authentication ──────────────────────────────────────────────────────
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ─── Account Lockout (django-axes) ──────────────────────────────────────
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25          # 15 minutes
AXES_RESET_ON_SUCCESS = True
AXES_LOCK_OUT_AT_FAILURE = True
AXES_ENABLED = True
AXES_LOCKOUT_TEMPLATE = 'accounts/locked_out.html'

# ─── Session & Security ──────────────────────────────────────────────────
SESSION_COOKIE_AGE = 28800            # 8 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# (Uncomment for production)
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'

# Used in email links
SITE_URL = 'http://127.0.0.1:8000'   # Change to your domain in production

# ── Email Configuration ────────────────────────────────
# Development — prints emails to the console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production — uncomment and fill in your SMTP details
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.jandn.mw'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'noreply@jandn.mw'
# EMAIL_HOST_PASSWORD = 'your-smtp-password'
# DEFAULT_FROM_EMAIL = 'J&N WMS <noreply@jandn.mw>'
# SERVER_EMAIL = 'noreply@jandn.mw'

DEFAULT_FROM_EMAIL = 'J&N WMS <noreply@jandn.mw>'

# ─── Static & Media ──────────────────────────────────────────────────────
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Unfold Admin Configuration ─────────────────────────────────────────

def safe_admin_changelist(model_name):
    """
    Returns the admin changelist URL name for the given model,
    e.g., 'admin:procurement_purchaserequest_changelist'.
    If the model is not registered in admin, returns None.
    """
    view_name = f'admin:{model_name}_changelist'
    try:
        reverse(view_name)   # Test if it resolves
        return view_name
    except NoReverseMatch:
        return None


def get_unfold_navigation(request):
    """
    Dynamically build the admin sidebar based on user permissions.
    Only modules the user has permission to view and that exist in admin
    will be shown.
    """
    user = request.user
    nav = []

    # ── Dashboard ──
    nav.append({
        "title": "Dashboard",
        "items": [
            {
                "title": "Dashboard",
                "icon": "dashboard",
                "link": "admin:index",
            },
        ],
    })

    # ── Inventory ──
    inv_items = []
    if user.has_perm('inventory.view_item'):
        url = safe_admin_changelist('inventory_item')
        if url:
            inv_items.append({"title": "Items", "icon": "inventory_2", "link": url})
    if user.has_perm('inventory.view_category'):
        url = safe_admin_changelist('inventory_category')
        if url:
            inv_items.append({"title": "Categories", "icon": "category", "link": url})
    if user.has_perm('inventory.view_warehouse'):
        url = safe_admin_changelist('inventory_warehouse')
        if url:
            inv_items.append({"title": "Warehouses", "icon": "warehouse", "link": url})
    if user.has_perm('inventory.view_stock'):
        url = safe_admin_changelist('inventory_stock')
        if url:
            inv_items.append({"title": "Stock Levels", "icon": "stacked_bar_chart", "link": url})
    if user.has_perm('inventory.view_stockmovement'):
        url = safe_admin_changelist('inventory_stockmovement')
        if url:
            inv_items.append({"title": "Stock Movements", "icon": "swap_horiz", "link": url})
    if inv_items:
        nav.append({"title": "Inventory", "collapsible": True, "items": inv_items})

    # ── Procurement ──
    proc_items = []
    if user.has_perm('procurement.view_supplier'):
        url = safe_admin_changelist('procurement_supplier')
        if url:
            proc_items.append({"title": "Suppliers", "icon": "local_shipping", "link": url})
    if user.has_perm('procurement.view_purchaserequest'):
        url = safe_admin_changelist('procurement_purchaserequest')
        if url:
            proc_items.append({"title": "Purchase Requests", "icon": "request_page", "link": url})
    if user.has_perm('procurement.view_purchaseorder'):
        url = safe_admin_changelist('procurement_purchaseorder')
        if url:
            proc_items.append({"title": "Purchase Orders", "icon": "receipt_long", "link": url})
    if user.has_perm('procurement.view_goodsreceipt'):
        url = safe_admin_changelist('procurement_goodsreceipt')
        if url:
            proc_items.append({"title": "Goods Receipts", "icon": "move_to_inbox", "link": url})
    if proc_items:
        nav.append({"title": "Procurement", "collapsible": True, "items": proc_items})

    # ── Operations ──
    ops_items = []
    if user.has_perm('operations.view_project'):
        url = safe_admin_changelist('operations_project')
        if url:
            ops_items.append({"title": "Projects", "icon": "construction", "link": url})
    if user.has_perm('operations.view_materialrequest'):
        url = safe_admin_changelist('operations_materialrequest')
        if url:
            ops_items.append({"title": "Material Requests", "icon": "request_page", "link": url})
    if ops_items:
        nav.append({"title": "Operations", "collapsible": True, "items": ops_items})

    # ── Assets ──
    assets_items = []
    if user.has_perm('assets.view_asset'):
        url = safe_admin_changelist('assets_asset')
        if url:
            assets_items.append({"title": "Assets", "icon": "build", "link": url})
    if user.has_perm('assets.view_assetassignment'):
        url = safe_admin_changelist('assets_assetassignment')
        if url:
            assets_items.append({"title": "Assignments", "icon": "assignment", "link": url})
    if user.has_perm('assets.view_maintenancerecord'):
        url = safe_admin_changelist('assets_maintenancerecord')
        if url:
            assets_items.append({"title": "Maintenance", "icon": "engineering", "link": url})
    if assets_items:
        nav.append({"title": "Assets", "collapsible": True, "items": assets_items})

    # ── Accounts ──
    accounts_items = []
    if user.has_perm('accounts.manage_users'):
        url = safe_admin_changelist('accounts_user')
        if url:
            accounts_items.append({"title": "Users", "icon": "people", "link": url})
    if user.has_perm('accounts.manage_roles'):
        url = safe_admin_changelist('accounts_role')
        if url:
            accounts_items.append({"title": "Roles", "icon": "admin_panel_settings", "link": url})
    if accounts_items:
        nav.append({"title": "Accounts", "collapsible": True, "items": accounts_items})

    return nav


UNFOLD = {
    "SITE_TITLE": "WMS",
    "SITE_HEADER": "Warehouse Management System",
    "SITE_SUBHEADER": "Construction & Manufacturing",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": get_unfold_navigation,
    },
}