# Generated by Django 5.2.15 on 2026-06-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_materialrequest', 'Can approve material request'), ('issue_materialrequest', 'Can issue materials from request')]},
        ),
    ]
