# Generated by Django 5.2.15 on 2026-06-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_purchaserequest', 'Can approve purchase request'), ('reject_purchaserequest', 'Can reject purchase request')]},
        ),
    ]
