# Generated by Django 5.2.15 on 2026-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_purchaserequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/purchase_orders/'),
        ),
    ]
