# Generated by Django 5.2.15 on 2026-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored Goods Receipt PDF for audit', null=True, upload_to='pdfs/grns/'),
        ),
    ]
