# Generated by Django 5.2.15 on 2026-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_reference_alter_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AIRTE', 'Airtel Money'), ('MPAMB', 'TNM Mpamba'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], max_length=20),
        ),
    ]
