# Generated by Django 5.2.15 on 2026-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/invoices/'),
        ),
    ]
