# Generated by Django 5.2.15 on 2026-07-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, help_text='Stored receipt PDF for audit', null=True, upload_to='pdfs/receipts/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored invoice PDF for audit', null=True, upload_to='pdfs/invoices/'),
        ),
    ]
