# Generated by Django 5.2.15 on 2026-07-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Stored Sales Order PDF for audit', null=True, upload_to='pdfs/sales_orders/'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Quotation this order was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
