# Generated by Django 5.2.15 on 2026-07-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_pdf_file'),
        ('sales', '0008_salesorder_pdf_file_salesorder_quotation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_approved',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='invoiced_quantity',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/invoices/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('AIRTE', 'Airtel Money'), ('MPAMB', 'TNM Mpamba'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/quotations/'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/sales_orders/'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
    ]
